# Generated by Django 3.2.10 on 2022-06-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('vote_count', models.IntegerField(default=0, editable=False)),
                ('party', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('u_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('mail_addr', models.CharField(max_length=50)),
                ('has_voted', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
