# Generated by Django 4.0.5 on 2022-06-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting', '0002_voter_public_e_sign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='public_e_sign_key',
            field=models.CharField(default=b'-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC0/7P/laiIXP7kCO5kPPxd4YuH\nwQ87RJ+N+WKbwjgG8pIP2LBW0p6flVnjmSQap0muEYdvMQvfVHrYVrgCfV5uNtlV\nV7xI5bZ3/VcfcInH9DN4ik786ZdbwIg1Zzjc1VdVP5U5tDJi/GSB1b5ODDL3qP2K\nkN+tbQ7sL9gs6NJN6wIDAQAB\n-----END PUBLIC KEY-----', max_length=350),
        ),
    ]
