# Generated by Django 3.2.9 on 2022-06-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting', '0004_auto_20220618_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='eligiblity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='public_e_sign_key',
            field=models.CharField(default=b'-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCxCtk5OLW83KlN5FdtG7w8Tne5\nYG8aRMRDJ91pqqAHGTroANekRtzcuVODzxvoRsIRmU4w7qWkY3V3vqc1xMCYAkah\nMnzvzy5iSW7adTAaCyU3wfzXVw//Q6hDs8Z7tgMzhkzAb5Mt+tOSUlMMfOZC2LTs\nvlOS5NTRTQq1f9mGgQIDAQAB\n-----END PUBLIC KEY-----', max_length=350),
        ),
    ]
