# Generated by Django 3.2.9 on 2022-06-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting', '0005_auto_20220618_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='eligiblity',
            new_name='eligibility',
        ),
        migrations.AlterField(
            model_name='voter',
            name='public_e_sign_key',
            field=models.CharField(default=b'-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDR4lWIJaledvWZVLIC5b+ebS/b\ne8fmm6rZrK6PfVWJlTfAPcZvXh6Nmqbn4xCK14fqBRzy8RromPQ3cbQFSDHDdzfh\n2Cd8J6hT8iOCUFTmsHlV3zoHTsx5d8deJp/rcH6GvC3oXPvqX0kttuc/YB2eEwzP\nq37ZsB463AYENvhaowIDAQAB\n-----END PUBLIC KEY-----', max_length=350),
        ),
    ]
