# Generated by Django 3.2.9 on 2022-06-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting', '0006_auto_20220618_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='party',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='vote_count',
        ),
        migrations.AlterField(
            model_name='voter',
            name='public_e_sign_key',
            field=models.CharField(default=b'-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDbBIl+D2gBMCzwdp2J2eu14pQu\nMm9wk2QSTO0ro5cMNL91vLdwnnWX62ZFFGOg35FITTNmGxzj9MCqOdJCleJGM37e\nNXgozSV1epox8qGu7CI3ApWhPy154UH5/A+QVV6S3olrY381FMDL6h0ImTEyaZHp\nmuFztMVPb3cGoBYp9wIDAQAB\n-----END PUBLIC KEY-----', max_length=350),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
